Repository KB-MoneyBunny/MoneyBunny-frontend, pull requests merged in 2025-08, with the labels that each got.

#33 Feature/asset(0731)자산페이지-계좌/카드탭 구현
  src/assets/images/icons/common/arrow_left.png
  src/assets/styles/item-styles.css
  src/assets/styles/overview-item-styles.css
  src/assets/utils/cardLogoMap.js
  src/assets/utils/spendingCategoryIcons.js
  src/pages/asset/AssetMain.vue
  src/pages/asset/account/AccountDetailPage.vue
  src/pages/asset/account/AccountItem.vue
  src/pages/asset/account/AccountSummaryCard.vue
  src/pages/asset/card/CardItem.vue
  src/pages/asset/card/CardOverviewItem.vue
  src/pages/asset/card/CardSummaryCard.vue
  src/pages/asset/common/AddItemModal.vue
  src/pages/asset/component/account/AccountDetail.vue
  src/pages/asset/component/account/AccountItem.vue
  src/pages/asset/component/account/AccountList.vue
  src/pages/asset/component/account/AccountOverviewItem.vue
  src/pages/asset/component/account/AccountOverviewList.vue
  src/pages/asset/component/card/CardControlButtons.vue
  src/pages/asset/component/card/CardDetail.vue
  src/pages/asset/component/card/CardItem.vue
  src/pages/asset/component/card/CardList.vue
  src/pages/asset/component/card/CardOverviewItem.vue
  src/pages/asset/component/card/CardOverviewList.vue
  src/pages/asset/component/common/AddItemButton.vue
  src/pages/asset/component/common/AddItemModal.vue
  src/pages/asset/component/common/AssetTabSwitcher.vue
  src/pages/asset/component/common/DeleteConfirmModal.vue
  src/pages/asset/component/common/DetailModal.vue
  src/pages/asset/component/common/LoginStep.vue
  src/pages/asset/component/common/NoDataCard.vue
  src/pages/asset/component/common/SelectItemsStep.vue
  src/pages/asset/component/common/SummaryCard.vue
  src/pages/asset/component/detail/DetailHeader.vue
  src/pages/asset/component/detail/DetailInfoCard.vue
  src/pages/asset/component/detail/TransactionFilter.vue
  src/pages/asset/component/detail/TransactionItem.vue
  src/pages/asset/component/detail/TransactionList.vue
  src/pages/asset/component/spending/BudgetStatus.vue
  src/pages/asset/component/spending/MonthlySpendingChart.vue
  src/pages/asset/component/spending/SpendingHistoryItem.vue
  src/pages/asset/component/spending/SpendingHistoryList.vue
  src/pages/asset/component/spending/ViewAllButton.vue
  src/pages/asset/component/total/AccountOverviewCard.vue
  src/pages/asset/component/total/CardOverviewCard.vue
  src/pages/asset/component/total/TotalAssetCard.vue
  src/pages/asset/component/utils/useMainItem.js
  src/pages/asset/spending/SpendingHistoryList.vue
  src/pages/asset/spending/ViewAllButton.vue
  src/pages/asset/tabs/AssetAccountTab.vue
  src/pages/asset/tabs/AssetCardTab.vue
  src/pages/asset/tabs/AssetTotalTab.vue
  src/router/index.js
Labels: feature

#39 Feature/find id link(0730)
  src/pages/auth/FindIdCodePage.vue
  src/pages/auth/FindIdPage.vue
  src/pages/auth/FindIdResultPage.vue
  src/pages/auth/FindPasswordPage.vue
  src/pages/auth/ResetPasswordPage.vue
  src/pages/auth/SignUpEmailVerifyPage.vue
  src/pages/auth/SignUpProfilePage.vue
  src/pages/mypage/settings/SettingMain.vue
  src/router/index.js
  vite.config.js
Labels: feature

#58 Feature/kakao share(0804)
  src/api/index.js
  src/pages/policy/detail/PolicyHeader.vue
  src/pages/policy/detail/ShareModal.vue
  src/router/index.js
  vite.config.js
Labels: feature

#59 Feature/spending(0804)
  src/assets/data/cards.json
  src/assets/data/spendings.json
  src/assets/images/icons/bunny/nodata_bunny.png
  src/assets/images/icons/bunny/nospending_bunny.png
  src/assets/utils/useSpendingData.js
  src/pages/asset/component/common/SummaryCard.vue
  src/pages/asset/component/detail/DetailHeader.vue
  src/pages/asset/component/detail/DetailInfoCard.vue
  src/pages/asset/component/spending/BudgetStatus.vue
  src/pages/asset/component/spending/CalendarSection.vue
  src/pages/asset/component/spending/CategoryChart.vue
  src/pages/asset/component/spending/CategoryDetailView.vue
  src/pages/asset/component/spending/CategoryDonutChart.vue
  src/pages/asset/component/spending/CategoryItem.vue
  src/pages/asset/component/spending/CategoryList.vue
  src/pages/asset/component/spending/MonthlySpendingChart.vue
  src/pages/asset/component/spending/SpendingHistoryItem.vue
  src/pages/asset/component/spending/SpendingHistoryList.vue
  src/pages/asset/component/spending/SpendingNodata.vue
  src/pages/asset/component/spending/TransactionItem.vue
  src/pages/asset/component/spending/ViewAllButton.vue
  src/pages/asset/tabs/AssetSpendingTab.vue
Labels: feature

#90 Feature/mypage link user(0807)
  src/pages/mypage/MypageMain.vue
Labels: feature

#94 Feature/mypage link user(0807)
  src/pages/mypage/modals/ChangePasswordModal.vue
Labels: feature

#136 Feature/asset(0808)
  src/assets/images/icons/bunny/moneybunny2.png
  src/pages/asset/AssetMain.vue
  src/pages/asset/component/common/AccountLoadingOverlay.vue
  src/pages/asset/component/common/AddItemModal.vue
  src/pages/asset/component/common/SelectItemsStep.vue
  src/pages/asset/component/common/SummaryCard.vue
  src/pages/asset/component/spending/CategoryDetailView.vue
  src/pages/asset/component/total/TotalAssetCard.vue
  src/pages/asset/tabs/AssetAccountTab.vue
  src/pages/asset/tabs/AssetCardTab.vue
  src/pages/asset/tabs/AssetSpendingTab.vue
Labels: bug, feature, design

#139 Feature/asset connect(0801) 자산 관련 각종 세세한 오류 및 로딩 수정
  src/api/assetApi.js
  src/assets/utils/useSpendingData.js
  src/pages/asset/AssetMain.vue
  src/pages/asset/component/account/AccountDetail.vue
  src/pages/asset/component/card/CardDetail.vue
  src/pages/asset/component/common/SelectItemsStep.vue
  src/pages/asset/component/detail/TransactionList.vue
  src/pages/asset/component/spending/CategoryDetailView.vue
  src/pages/asset/tabs/AssetSpendingTab.vue
  src/pages/mypage/settings/SettingMain.vue
  src/stores/uiFlags.js
  vite.config.js
Labels: bug, feature

#142 정책 공개 페이지 및 로그인 안내 페이지 생성
  src/pages/auth/LoginPage.vue
  src/pages/auth/SignUpProfilePage.vue
  src/pages/home/GuestGatePage.vue
  src/pages/home/HomeGuestPanel.vue
  src/pages/policy/detail/PolicyDetailPage.vue
  src/router/index.js
  src/stores/auth.js
  vite.config.js
Labels: feature

#143 Feature/asset(0808)
  src/assets/images/icons/common/copy.png
  src/assets/images/icons/savings_category/category_car.png
  src/assets/images/icons/savings_category/category_education.png
  src/assets/images/icons/savings_category/category_emergency_fund.png
  src/assets/images/icons/savings_category/category_etc.png
  src/assets/images/icons/savings_category/category_house_purchase.png
  src/assets/images/icons/savings_category/category_retirement_fund.png
  src/assets/images/icons/savings_category/category_travel.png
  src/assets/images/icons/savings_category/category_wedding_fund.png
  src/pages/asset/component/account/AccountItem.vue
  src/pages/asset/component/common/SummaryCard.vue
  src/pages/asset/component/spending/CategoryChart.vue
  src/pages/asset/component/spending/CategoryList.vue
  src/pages/asset/component/spending/SpendingNodata.vue
  src/pages/asset/component/total/AccountOverviewCard.vue
  src/pages/asset/component/total/CardOverviewCard.vue
  src/router/index.js
  vite.config.js
Labels: feature, design
